# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hitl_app_copy.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BehaviorAnalysis(object):
    def setupUi(self, BehaviorAnalysis):
        BehaviorAnalysis.setObjectName("BehaviorAnalysis")
        BehaviorAnalysis.resize(840, 800)
        BehaviorAnalysis.setDockOptions(QtWidgets.QMainWindow.AllowNestedDocks|QtWidgets.QMainWindow.AllowTabbedDocks|QtWidgets.QMainWindow.AnimatedDocks)
        BehaviorAnalysis.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(BehaviorAnalysis)
        self.centralwidget.setObjectName("centralwidget")
        self.urlLabel = QtWidgets.QLabel(self.centralwidget)
        self.urlLabel.setGeometry(QtCore.QRect(30, 30, 171, 31))
        self.urlLabel.setStyleSheet("font: 75 14pt \"Calibri\";")
        self.urlLabel.setTextFormat(QtCore.Qt.MarkdownText)
        self.urlLabel.setWordWrap(False)
        self.urlLabel.setOpenExternalLinks(False)
        self.urlLabel.setObjectName("urlLabel")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(20, 190, 801, 581))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setFocusPolicy(QtCore.Qt.NoFocus)
        self.scrollArea.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.scrollArea.setAcceptDrops(False)
        self.scrollArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 799, 579))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.result_box = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.result_box.setGeometry(QtCore.QRect(0, 0, 801, 571))
        self.result_box.setMaximumSize(QtCore.QSize(16777215, 1061))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(11)
        self.result_box.setFont(font)
        self.result_box.setToolTipDuration(-2)
        self.result_box.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.result_box.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.result_box.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.result_box.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.result_box.setLineWrapColumnOrWidth(80)
        self.result_box.setReadOnly(False)
        self.result_box.setMarkdown("")
        self.result_box.setOverwriteMode(False)
        self.result_box.setObjectName("result_box")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.lineEdit_url = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_url.setGeometry(QtCore.QRect(30, 70, 761, 31))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(10)
        self.lineEdit_url.setFont(font)
        self.lineEdit_url.setText("")
        self.lineEdit_url.setObjectName("lineEdit_url")
        self.btn_run = QtWidgets.QPushButton(self.centralwidget)
        self.btn_run.setEnabled(False)
        self.btn_run.setGeometry(QtCore.QRect(710, 110, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_run.setFont(font)
        self.btn_run.setMouseTracking(True)
        self.btn_run.setDefault(False)
        self.btn_run.setObjectName("btn_run")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(100, 130, 381, 23))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(14)
        self.progressBar.setFont(font)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.progressLabel = QtWidgets.QLabel(self.centralwidget)
        self.progressLabel.setGeometry(QtCore.QRect(30, 130, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.progressLabel.setFont(font)
        self.progressLabel.setObjectName("progressLabel")
        self.btn_stp = QtWidgets.QPushButton(self.centralwidget)
        self.btn_stp.setGeometry(QtCore.QRect(640, 20, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_stp.setFont(font)
        self.btn_stp.setObjectName("btn_stp")
        self.btn_clr = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clr.setGeometry(QtCore.QRect(730, 20, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_clr.setFont(font)
        self.btn_clr.setObjectName("btn_clr")
        BehaviorAnalysis.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BehaviorAnalysis)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 840, 21))
        self.menubar.setObjectName("menubar")
        BehaviorAnalysis.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BehaviorAnalysis)
        self.statusbar.setObjectName("statusbar")
        BehaviorAnalysis.setStatusBar(self.statusbar)

        self.retranslateUi(BehaviorAnalysis)
        self.btn_clr.clicked.connect(self.lineEdit_url.clear) # type: ignore
        self.btn_clr.clicked.connect(self.result_box.clear) # type: ignore
        self.btn_clr.clicked.connect(self.progressBar.reset) # type: ignore
        self.lineEdit_url.textChanged.connect(self.update_btn_run_state) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(BehaviorAnalysis)
        
    def update_btn_run_state(self):
        text = self.lineEdit_url.text().strip()
        self.btn_run.setEnabled(bool(text)) # type: ignore 
        
    def process_done(self, result_text):
        print(f"DEBUG: process_done called with result_text: {result_text}")
        self.result_box.setPlainText(result_text)

    def retranslateUi(self, BehaviorAnalysis):
        _translate = QtCore.QCoreApplication.translate
        BehaviorAnalysis.setWindowTitle(_translate("BehaviorAnalysis", "MainWindow"))
        self.urlLabel.setText(_translate("BehaviorAnalysis", "### Insert URL:"))
        self.result_box.setHtml(_translate("BehaviorAnalysis", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Consolas\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.result_box.setPlaceholderText(_translate("BehaviorAnalysis", "Result Will display Here"))
        self.lineEdit_url.setPlaceholderText(_translate("BehaviorAnalysis", "https://www.samplevideolink.com/path/to/video.mp4"))
        self.btn_run.setText(_translate("BehaviorAnalysis", "Run"))
        self.progressLabel.setText(_translate("BehaviorAnalysis", "Progress:"))
        self.btn_stp.setText(_translate("BehaviorAnalysis", "Stop"))
        self.btn_clr.setText(_translate("BehaviorAnalysis", "Clear"))
