# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hitl_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BehaviorAnalysis(object):
    def setupUi(self, BehaviorAnalysis):
        BehaviorAnalysis.setObjectName("BehaviorAnalysis")
        BehaviorAnalysis.resize(849, 803)
        BehaviorAnalysis.setWindowTitle("MainWindow")
        BehaviorAnalysis.setDockOptions(QtWidgets.QMainWindow.AllowNestedDocks | QtWidgets.QMainWindow.AllowTabbedDocks | QtWidgets.QMainWindow.AnimatedDocks)
        BehaviorAnalysis.setUnifiedTitleAndToolBarOnMac(False)

        self.centralwidget = QtWidgets.QWidget(BehaviorAnalysis)
        self.centralwidget.setObjectName("centralwidget")

        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 171, 31))
        self.label.setStyleSheet("font: 75 14pt \"Calibri\";")
        self.label.setText("### Insert URL:")
        self.label.setTextFormat(QtCore.Qt.MarkdownText)
        self.label.setObjectName("label")

        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(39, 189, 751, 561))
        self.scrollArea.setObjectName("scrollArea")

        BehaviorAnalysis.setCentralWidget(self.centralwidget)

        self.retranslateUi(BehaviorAnalysis)
        QtCore.QMetaObject.connectSlotsByName(BehaviorAnalysis)

    def retranslateUi(self, BehaviorAnalysis):
        pass
