# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hitl_app_copy.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BehaviorAnalysis(object):
    def setupUi(self, BehaviorAnalysis):
        BehaviorAnalysis.setObjectName("BehaviorAnalysis")
        BehaviorAnalysis.resize(960, 760)
        BehaviorAnalysis.setMinimumSize(QtCore.QSize(800, 640))
        self.centralwidget = QtWidgets.QWidget(BehaviorAnalysis)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setStyleSheet("""
            QWidget#centralwidget { background: #0e1117; color: #e9edf5; }
            QLabel { color: #c7cfde; }
            QLineEdit, QTextEdit {
                background: #121826;
                border: 1px solid #1f2633;
                border-radius: 10px;
                padding: 10px;
                color: #e9edf5;
            }
            QPushButton {
                border-radius: 10px;
                padding: 10px 14px;
                font-weight: 600;
                color: #0d131c;
            }
            QPushButton#primary {
                background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #6df3c5, stop:1 #7bb6ff);
                color: #0c1118;
            }
            QPushButton#ghost {
                background: transparent;
                border: 1px solid #2a3040;
                color: #c7cfde;
            }
            QProgressBar {
                background: #121826;
                border: 1px solid #1f2633;
                border-radius: 12px;
                text-align: center;
                color: #c7cfde;
            }
            QProgressBar::chunk {
                background: qlineargradient(x1:0, y1:0, x2:1, y2:0, stop:0 #6df3c5, stop:1 #7bb6ff);
                border-radius: 12px;
            }
        """)

        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setContentsMargins(22, 18, 22, 18)
        self.mainLayout.setSpacing(14)

        self.header = QtWidgets.QLabel(self.centralwidget)
        header_font = QtGui.QFont("Segoe UI", 18, QtGui.QFont.Bold)
        self.header.setFont(header_font)
        self.header.setText("Behavior Analysis")
        self.mainLayout.addWidget(self.header)

        self.subheader = QtWidgets.QLabel(self.centralwidget)
        sub_font = QtGui.QFont("Segoe UI", 11)
        self.subheader.setFont(sub_font)
        self.subheader.setWordWrap(True)
        self.subheader.setText("Paste a video URL, run the pipeline, and review transcript, indicators, and behavior cues in one place.")
        self.mainLayout.addWidget(self.subheader)

        self.inputCard = QtWidgets.QFrame(self.centralwidget)
        self.inputCard.setObjectName("inputCard")
        self.inputCard.setStyleSheet("QFrame#inputCard { background:#0b0f19; border:1px solid #1f2633; border-radius:14px; }")
        inputLayout = QtWidgets.QVBoxLayout(self.inputCard)
        inputLayout.setContentsMargins(16, 14, 16, 14)
        inputLayout.setSpacing(10)

        self.urlLabel = QtWidgets.QLabel(self.inputCard)
        self.urlLabel.setFont(QtGui.QFont("Segoe UI", 10, QtGui.QFont.Bold))
        self.urlLabel.setText("Video URL")
        inputLayout.addWidget(self.urlLabel)

        self.lineEdit_url = QtWidgets.QLineEdit(self.inputCard)
        self.lineEdit_url.setPlaceholderText("https://www.samplevideolink.com/path/to/video.mp4")
        self.lineEdit_url.textChanged.connect(self.update_btn_run_state)
        inputLayout.addWidget(self.lineEdit_url)

        buttonsRow = QtWidgets.QHBoxLayout()
        buttonsRow.setSpacing(8)

        self.btn_run = QtWidgets.QPushButton(self.inputCard)
        self.btn_run.setObjectName("primary")
        self.btn_run.setText("Run Analysis")
        self.btn_run.setEnabled(False)
        buttonsRow.addWidget(self.btn_run)

        self.btn_stp = QtWidgets.QPushButton("Stop", self.inputCard)
        self.btn_stp.setObjectName("ghost")
        buttonsRow.addWidget(self.btn_stp)

        self.btn_clr = QtWidgets.QPushButton("Clear", self.inputCard)
        self.btn_clr.setObjectName("ghost")
        buttonsRow.addWidget(self.btn_clr)

        buttonsRow.addStretch()
        inputLayout.addLayout(buttonsRow)

        self.progressLabel = QtWidgets.QLabel(self.inputCard)
        self.progressLabel.setFont(QtGui.QFont("Segoe UI", 9, QtGui.QFont.Bold))
        self.progressLabel.setText("Progress")
        inputLayout.addWidget(self.progressLabel)

        self.progressBar = QtWidgets.QProgressBar(self.inputCard)
        self.progressBar.setProperty("value", 0)
        inputLayout.addWidget(self.progressBar)

        self.mainLayout.addWidget(self.inputCard)

        self.resultCard = QtWidgets.QFrame(self.centralwidget)
        self.resultCard.setObjectName("resultCard")
        self.resultCard.setStyleSheet("QFrame#resultCard { background:#0b0f19; border:1px solid #1f2633; border-radius:14px; }")
        resultLayout = QtWidgets.QVBoxLayout(self.resultCard)
        resultLayout.setContentsMargins(16, 14, 16, 14)
        resultLayout.setSpacing(10)

        self.resultTitle = QtWidgets.QLabel(self.resultCard)
        self.resultTitle.setFont(QtGui.QFont("Segoe UI", 11, QtGui.QFont.Bold))
        self.resultTitle.setText("Transcript & Signals")
        resultLayout.addWidget(self.resultTitle)

        self.result_box = QtWidgets.QTextEdit(self.resultCard)
        self.result_box.setAcceptRichText(False)
        self.result_box.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.result_box.setFont(QtGui.QFont("Consolas", 11))
        self.result_box.setPlaceholderText("Result will display here")
        resultLayout.addWidget(self.result_box)

        self.mainLayout.addWidget(self.resultCard)

        BehaviorAnalysis.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BehaviorAnalysis)
        self.menubar.setObjectName("menubar")
        BehaviorAnalysis.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BehaviorAnalysis)
        self.statusbar.setObjectName("statusbar")
        BehaviorAnalysis.setStatusBar(self.statusbar)

        self.retranslateUi(BehaviorAnalysis)
        QtCore.QMetaObject.connectSlotsByName(BehaviorAnalysis)

    def update_btn_run_state(self):
        text = self.lineEdit_url.text().strip()
        self.btn_run.setEnabled(bool(text)) # type: ignore 
        
    def process_done(self, result_text):
        print(f"DEBUG: process_done called with result_text: {result_text}")
        self.result_box.setPlainText(result_text)

    def retranslateUi(self, BehaviorAnalysis):
        _translate = QtCore.QCoreApplication.translate
        BehaviorAnalysis.setWindowTitle(_translate("BehaviorAnalysis", "Behavior Analysis"))
