# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hitl_app.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BehaviorAnalysis(object):
    def setupUi(self, BehaviorAnalysis):
        BehaviorAnalysis.setObjectName("Behavioral Analysis Tool")
        BehaviorAnalysis.resize(849, 804)
        self.centralwidget = QtWidgets.QWidget(BehaviorAnalysis)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 30, 171, 31))
        self.label.setStyleSheet("font: 75 14pt \"Calibri\";")
        self.label.setTextFormat(QtCore.Qt.MarkdownText)
        self.label.setObjectName("label")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(39, 189, 751, 561))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 749, 559))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.result_box = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.result_box.setGeometry(QtCore.QRect(3, 0, 751, 1061))
        self.result_box.setMaximumSize(QtCore.QSize(16777215, 1061))
        self.result_box.setReadOnly(True)
        self.result_box.setMarkdown("")
        self.result_box.setObjectName("result_box")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.lineEdit_url = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_url.setGeometry(QtCore.QRect(30, 70, 761, 31))
        self.lineEdit_url.setObjectName("lineEdit_url")
        self.btn_run = QtWidgets.QPushButton(self.centralwidget)
        self.btn_run.setGeometry(QtCore.QRect(710, 110, 75, 23))
        self.btn_run.setObjectName("btn_run")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(100, 130, 381, 23))
        self.progressBar.setValue(0)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 130, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        BehaviorAnalysis.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BehaviorAnalysis)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 849, 21))
        self.menubar.setObjectName("menubar")
        BehaviorAnalysis.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BehaviorAnalysis)
        self.statusbar.setObjectName("statusbar")
        BehaviorAnalysis.setStatusBar(self.statusbar)

        self.retranslateUi(BehaviorAnalysis)
        QtCore.QMetaObject.connectSlotsByName(BehaviorAnalysis)

    def retranslateUi(self, BehaviorAnalysis):
        _translate = QtCore.QCoreApplication.translate
        BehaviorAnalysis.setWindowTitle(_translate("BehaviorAnalysis", "BehaviorAnalysis"))
        self.label.setText(_translate("BehaviorAnalysis", "### Insert URL:"))
        self.result_box.setPlaceholderText(_translate("BehaviorAnalysis", "Result"))
        self.lineEdit_url.setPlaceholderText(_translate("BehaviorAnalysis", "https://www.inserturlhere.com/path/to/video.mp4"))
        self.btn_run.setText(_translate("BehaviorAnalysis", "Run"))
        self.label_2.setText(_translate("BehaviorAnalysis", "Progress:"))
