# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hitl_app_copy.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BehaviorAnalysis(object):
    def setupUi(self, BehaviorAnalysis):
        BehaviorAnalysis.setObjectName("BehaviorAnalysis")
        BehaviorAnalysis.resize(1400, 900)
        BehaviorAnalysis.setMinimumSize(QtCore.QSize(1200, 800))
        self.centralwidget = QtWidgets.QWidget(BehaviorAnalysis)
        self.centralwidget.setObjectName("centralwidget")
        self.centralwidget.setStyleSheet("""
            QWidget#centralwidget {
                background: qlineargradient(x1:0, y1:0, x2:1, y2:1,
                    stop:0 #0a0e1a, stop:0.5 #0d1117, stop:1 #0a0e1a);
                color: #00ff88;
            }
            QLabel {
                color: #00ff88;
                font-family: 'Consolas', 'Courier New', monospace;
            }
            QLabel#headerLabel {
                color: #00ff88;
                font-size: 32px;
                font-weight: bold;
                letter-spacing: 3px;
                text-transform: uppercase;
            }
            QLabel#subheaderLabel {
                color: #00d4ff;
                font-size: 11px;
                letter-spacing: 1px;
            }
            QLabel#sectionLabel {
                color: #00ff88;
                font-size: 13px;
                font-weight: bold;
                letter-spacing: 2px;
                border-left: 3px solid #00ff88;
                padding-left: 10px;
            }
            QLineEdit {
                background: rgba(0, 20, 40, 0.7);
                border: 2px solid #00ff88;
                border-radius: 5px;
                padding: 12px;
                color: #00ff88;
                font-family: 'Consolas', 'Courier New', monospace;
                font-size: 12px;
                selection-background-color: #00ff88;
                selection-color: #000;
            }
            QLineEdit:focus {
                border: 2px solid #00d4ff;
                background: rgba(0, 212, 255, 0.1);
            }
            QTextEdit {
                background: rgba(0, 10, 20, 0.9);
                border: 2px solid #00ff88;
                border-radius: 5px;
                padding: 15px;
                color: #00ff88;
                font-family: 'Consolas', 'Courier New', monospace;
                font-size: 11px;
                selection-background-color: #00ff88;
                selection-color: #000;
            }
            QPushButton {
                border: 2px solid #00ff88;
                border-radius: 5px;
                padding: 12px 24px;
                font-weight: bold;
                font-size: 13px;
                font-family: 'Consolas', 'Courier New', monospace;
                letter-spacing: 2px;
                color: #00ff88;
                background: rgba(0, 255, 136, 0.1);
            }
            QPushButton:hover {
                background: rgba(0, 255, 136, 0.3);
                border: 2px solid #00d4ff;
                color: #00d4ff;
            }
            QPushButton:pressed {
                background: rgba(0, 255, 136, 0.5);
            }
            QPushButton#primary {
                background: rgba(0, 255, 136, 0.2);
                border: 3px solid #00ff88;
                color: #00ff88;
            }
            QPushButton#primary:hover {
                background: #00ff88;
                color: #000;
            }
            QPushButton#danger {
                background: rgba(255, 0, 100, 0.1);
                border: 2px solid #ff0066;
                color: #ff0066;
            }
            QPushButton#danger:hover {
                background: rgba(255, 0, 100, 0.3);
            }
            QPushButton#ghost {
                background: transparent;
                border: 2px solid #00d4ff;
                color: #00d4ff;
            }
            QPushButton#ghost:hover {
                background: rgba(0, 212, 255, 0.2);
            }
            QProgressBar {
                background: rgba(0, 20, 40, 0.7);
                border: 2px solid #00ff88;
                border-radius: 10px;
                text-align: center;
                color: #00ff88;
                font-family: 'Consolas', 'Courier New', monospace;
                font-weight: bold;
                font-size: 12px;
                height: 30px;
            }
            QProgressBar::chunk {
                background: qlineargradient(x1:0, y1:0, x2:1, y2:0,
                    stop:0 #00ff88, stop:0.5 #00d4ff, stop:1 #00ff88);
                border-radius: 8px;
            }
            QFrame#panel {
                background: rgba(0, 20, 40, 0.5);
                border: 2px solid #00ff88;
                border-radius: 10px;
            }
            QStatusBar {
                background: #0a0e1a;
                color: #00ff88;
                border-top: 2px solid #00ff88;
                font-family: 'Consolas', 'Courier New', monospace;
            }
        """)

        self.mainLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainLayout.setContentsMargins(30, 25, 30, 25)
        self.mainLayout.setSpacing(20)

        # Header section
        self.header = QtWidgets.QLabel(self.centralwidget)
        self.header.setObjectName("headerLabel")
        header_font = QtGui.QFont("Consolas", 32, QtGui.QFont.Bold)
        self.header.setFont(header_font)
        self.header.setText("◢ OVERWATCH ◣")
        self.header.setAlignment(QtCore.Qt.AlignCenter)
        self.mainLayout.addWidget(self.header)

        self.subheader = QtWidgets.QLabel(self.centralwidget)
        self.subheader.setObjectName("subheaderLabel")
        sub_font = QtGui.QFont("Consolas", 11)
        self.subheader.setFont(sub_font)
        self.subheader.setWordWrap(True)
        self.subheader.setText("BEHAVIORAL INTELLIGENCE ANALYSIS SYSTEM  |  REAL-TIME SURVEILLANCE & PATTERN RECOGNITION")
        self.subheader.setAlignment(QtCore.Qt.AlignCenter)
        self.mainLayout.addWidget(self.subheader)

        # Add spacing
        self.mainLayout.addSpacing(10)

        self.inputCard = QtWidgets.QFrame(self.centralwidget)
        self.inputCard.setObjectName("panel")
        inputLayout = QtWidgets.QVBoxLayout(self.inputCard)
        inputLayout.setContentsMargins(25, 20, 25, 20)
        inputLayout.setSpacing(15)

        self.urlLabel = QtWidgets.QLabel(self.inputCard)
        self.urlLabel.setObjectName("sectionLabel")
        self.urlLabel.setFont(QtGui.QFont("Consolas", 13, QtGui.QFont.Bold))
        self.urlLabel.setText("[ TARGET VIDEO SOURCE ]")
        inputLayout.addWidget(self.urlLabel)

        self.lineEdit_url = QtWidgets.QLineEdit(self.inputCard)
        self.lineEdit_url.setPlaceholderText("ENTER VIDEO URL FOR ANALYSIS...")
        self.lineEdit_url.setMinimumHeight(45)
        self.lineEdit_url.textChanged.connect(self.update_btn_run_state)
        inputLayout.addWidget(self.lineEdit_url)

        buttonsRow = QtWidgets.QHBoxLayout()
        buttonsRow.setSpacing(15)

        self.btn_run = QtWidgets.QPushButton(self.inputCard)
        self.btn_run.setObjectName("primary")
        self.btn_run.setText("▶ INITIATE ANALYSIS")
        self.btn_run.setEnabled(False)
        self.btn_run.setMinimumHeight(50)
        buttonsRow.addWidget(self.btn_run)

        self.btn_stp = QtWidgets.QPushButton("■ TERMINATE", self.inputCard)
        self.btn_stp.setObjectName("danger")
        self.btn_stp.setMinimumHeight(50)
        buttonsRow.addWidget(self.btn_stp)

        self.btn_clr = QtWidgets.QPushButton("◆ RESET", self.inputCard)
        self.btn_clr.setObjectName("ghost")
        self.btn_clr.setMinimumHeight(50)
        buttonsRow.addWidget(self.btn_clr)

        inputLayout.addLayout(buttonsRow)

        self.progressLabel = QtWidgets.QLabel(self.inputCard)
        self.progressLabel.setObjectName("sectionLabel")
        self.progressLabel.setFont(QtGui.QFont("Consolas", 13, QtGui.QFont.Bold))
        self.progressLabel.setText("[ ANALYSIS PROGRESS ]")
        inputLayout.addWidget(self.progressLabel)

        self.progressBar = QtWidgets.QProgressBar(self.inputCard)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setMinimumHeight(35)
        inputLayout.addWidget(self.progressBar)

        self.mainLayout.addWidget(self.inputCard)

        # Create horizontal split layout for video and results
        self.contentSplitter = QtWidgets.QHBoxLayout()
        self.contentSplitter.setSpacing(20)

        # Left side: Video display panel
        self.videoCard = QtWidgets.QFrame(self.centralwidget)
        self.videoCard.setObjectName("panel")
        videoLayout = QtWidgets.QVBoxLayout(self.videoCard)
        videoLayout.setContentsMargins(25, 20, 25, 20)
        videoLayout.setSpacing(15)

        self.videoTitle = QtWidgets.QLabel(self.videoCard)
        self.videoTitle.setObjectName("sectionLabel")
        self.videoTitle.setFont(QtGui.QFont("Consolas", 13, QtGui.QFont.Bold))
        self.videoTitle.setText("[ LIVE ANALYSIS FEED ]")
        videoLayout.addWidget(self.videoTitle)

        self.video_display = QtWidgets.QLabel(self.videoCard)
        self.video_display.setMinimumSize(QtCore.QSize(640, 480))
        self.video_display.setMaximumSize(QtCore.QSize(800, 600))
        self.video_display.setStyleSheet("""
            QLabel {
                background: #000;
                border: 2px solid #00ff88;
                border-radius: 5px;
                color: #00ff88;
                font-size: 16px;
                qproperty-alignment: AlignCenter;
            }
        """)
        self.video_display.setText("◢ AWAITING VIDEO FEED ◣")
        self.video_display.setScaledContents(False)
        self.video_display.setAlignment(QtCore.Qt.AlignCenter)
        videoLayout.addWidget(self.video_display)

        self.contentSplitter.addWidget(self.videoCard, 3)  # 60% width

        # Right side: Results panel (smaller)
        self.resultCard = QtWidgets.QFrame(self.centralwidget)
        self.resultCard.setObjectName("panel")
        resultLayout = QtWidgets.QVBoxLayout(self.resultCard)
        resultLayout.setContentsMargins(25, 20, 25, 20)
        resultLayout.setSpacing(15)

        self.resultTitle = QtWidgets.QLabel(self.resultCard)
        self.resultTitle.setObjectName("sectionLabel")
        self.resultTitle.setFont(QtGui.QFont("Consolas", 13, QtGui.QFont.Bold))
        self.resultTitle.setText("[ INTEL REPORT ]")
        resultLayout.addWidget(self.resultTitle)

        self.result_box = QtWidgets.QTextEdit(self.resultCard)
        self.result_box.setAcceptRichText(False)
        self.result_box.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.result_box.setFont(QtGui.QFont("Consolas", 10))
        self.result_box.setPlaceholderText(">>> AWAITING DATA...\n>>> SYSTEM READY")
        resultLayout.addWidget(self.result_box)

        self.contentSplitter.addWidget(self.resultCard, 2)  # 40% width

        self.mainLayout.addLayout(self.contentSplitter)

        BehaviorAnalysis.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(BehaviorAnalysis)
        self.menubar.setObjectName("menubar")
        BehaviorAnalysis.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(BehaviorAnalysis)
        self.statusbar.setObjectName("statusbar")
        BehaviorAnalysis.setStatusBar(self.statusbar)

        self.retranslateUi(BehaviorAnalysis)
        QtCore.QMetaObject.connectSlotsByName(BehaviorAnalysis)

    def update_btn_run_state(self):
        text = self.lineEdit_url.text().strip()
        self.btn_run.setEnabled(bool(text)) # type: ignore 
        
    def process_done(self, result_text):
        print(f"DEBUG: process_done called with result_text: {result_text}")
        self.result_box.setPlainText(result_text)

    def retranslateUi(self, BehaviorAnalysis):
        _translate = QtCore.QCoreApplication.translate
        BehaviorAnalysis.setWindowTitle(_translate("BehaviorAnalysis", "OVERWATCH :: Behavioral Intelligence Analysis System"))
